{{- if .Values.configSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "paperclip.fullname" . }}-config
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.configSecret.key }}
  refreshInterval: {{ .Values.configSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ include "paperclip.fullname" . }}-config
{{- end }}
