{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (include "paperclip.fullname" .) .Values.externalSecret.name }}
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ default (include "paperclip.fullname" .) .Values.externalSecret.key }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ default (include "paperclip.fullname" .) .Values.externalSecret.targetName }}
{{- end }}
